### PR TITLE
Add CodeDeploy Deployment Hook Support

### PR DESCRIPTION
**Pull request by chrischildresssg**
## Change description

> Add support for declaring Lambdas which should be invoked as a CodeDeploy application deployment hook.
[Appspec Hooks Reference](https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-ecs) 

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> None

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by angellopez-sg** [comment]
@chrischildresssg Have you applied it? The complete example is quite complex.

**Comment by chrischildresssg** [comment]
> @chrischildresssg Have you applied it? The complete example is quite complex.

Yes, I've applied this in practice and it works well.

**Review by angellopez-sg — DISMISSED** [review]
@chrischildresssg  Why did you change the version of the ecs-service module in the README? I've also seen you've removed the formatting for the example in the same file.

These are the only doubts I have.

**Comment by chrischildresssg** [comment]
> @chrischildresssg Why did you change the version of the ecs-service module in the README? I've also seen you've removed the formatting for the example in the same file.
> 
> These are the only doubts I have.

For the version in the README - I'll update that.  We're using pessimistic versioning.  While the updated value would certainly allow for the anticipated release version, I'll be more clear.

For the formatting, that's actually a bug in terraform-docs with the way it handles the "hcl" type of text block.  I need to inject that as a separate file.

**Review by angellopez-sg — APPROVED** [review]
LGTM

**Pull request merged**
